//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.HWeatherRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HWeatherRef.IHWeatherService")]
    public interface IHWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHWeatherService/getHistoricalWeatherData", ReplyAction="http://tempuri.org/IHWeatherService/getHistoricalWeatherDataResponse")]
        string getHistoricalWeatherData(System.DateTime startDate, System.DateTime endDate, decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHWeatherService/getHistoricalWeatherData", ReplyAction="http://tempuri.org/IHWeatherService/getHistoricalWeatherDataResponse")]
        System.Threading.Tasks.Task<string> getHistoricalWeatherDataAsync(System.DateTime startDate, System.DateTime endDate, decimal latitude, decimal longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHWeatherServiceChannel : WeatherApp.HWeatherRef.IHWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HWeatherServiceClient : System.ServiceModel.ClientBase<WeatherApp.HWeatherRef.IHWeatherService>, WeatherApp.HWeatherRef.IHWeatherService {
        
        public HWeatherServiceClient() {
        }
        
        public HWeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HWeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HWeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HWeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getHistoricalWeatherData(System.DateTime startDate, System.DateTime endDate, decimal latitude, decimal longitude) {
            return base.Channel.getHistoricalWeatherData(startDate, endDate, latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<string> getHistoricalWeatherDataAsync(System.DateTime startDate, System.DateTime endDate, decimal latitude, decimal longitude) {
            return base.Channel.getHistoricalWeatherDataAsync(startDate, endDate, latitude, longitude);
        }
    }
}
